In [3]:
import pandas as pd
df=pd.read_csv("C:/Users/Vivobook/Downloads/python-project/crime_incidents_messy.csv")
# we see first 5 rows - a quick peek
df.head()

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,...,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,...,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,...,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,...,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,...,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   str
 1   crime_type          5250 non-null   str
 2   district            5250 non-null   str
 3   city                5250 non-null   str
 4   state               5250 non-null   str
 5   address             5250 non-null   str
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   str
 9   officer_id          5250 non-null   str
 10  officer_first_name  5250 non-null   str
 11  officer_last_name   5250 non-null   str
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   str
 14  suspect_first_name  4440 non-null   str
 15  suspect_last_name   4440 non-null   str
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   str
 18  suspect_race        3649 non-null   str
 19  victim_id           4993 non-null   str
 20  victim_first_name   4993 non-null   str
 21  victim_last_name    4993 non-null   str
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   str
 24  victim_phone        4194 non-null   str
 25  weapon_used         4280 non-null   str
 26  severity            4895 non-null   str
 27  case_status         4519 non-null   str
 28  resolution          4299 non-null   str
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   str
 31  reported_online     4746 non-null   str
 32  notes               4181 non-null   str
dtypes: float64(6), str(27)
memory usage: 1.3 MB

In [5]:
df.isnull()

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5245,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,True,True
5246,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
5247,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
5248,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
5249,False,False,False,False,False,False,False,False,False,False,...,True,True,True,False,False,False,False,False,False,False

In [6]:
# sum of the null values - so after cleaning we can see that all of them cleaned
df.isnull().sum()

incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude               258
longitude              289
incident_datetime      340
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           312
suspect_id             810
suspect_first_name     810
suspect_last_name      810
suspect_age           1097
suspect_gender        1413
suspect_race          1601
victim_id              257
victim_first_name      257
victim_last_name       257
victim_age             562
victim_gender         1000
victim_phone          1056
weapon_used            970
severity               355
case_status            731
resolution             951
num_arrests            333
property_loss_usd      436
reported_online        504
notes                 1069
dtype: int64

In [7]:
df.shape

(5250, 33)

In [8]:
# fill numeric columns with median
for col in ['latitude', 'longitude', 'suspect_age', 'victim_age', 'num_arrests']:
    df[col] = df[col].fillna(df[col].median())

In [9]:
# there are no null values in columns mentioned in the loop
df.isnull().sum()

incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude                 0
longitude                0
incident_datetime      340
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           312
suspect_id             810
suspect_first_name     810
suspect_last_name      810
suspect_age              0
suspect_gender        1413
suspect_race          1601
victim_id              257
victim_first_name      257
victim_last_name       257
victim_age               0
victim_gender         1000
victim_phone          1056
weapon_used            970
severity               355
case_status            731
resolution             951
num_arrests              0
property_loss_usd      436
reported_online        504
notes                 1069
dtype: int64

In [10]:
# missing values in number of arrests columns mean zero arrests
df['num_arrests']=df['num_arrests'].fillna(0)

In [11]:
# fill nulls in categorical columns with unknown
unknown_cols = ['suspect_id','suspect_first_name','suspect_last_name',
                'suspect_gender','suspect_race','victim_id','victim_first_name','victim_last_name',
                                'victim_gender','victim_phone','weapon_used','case_status','resolution',
                'reported_online','severity']

In [12]:
for col in unknown_cols :
    df[col]=df[col].fillna('Unknown')

In [13]:
df.isnull().sum()

incident_id              0
crime_type               0
district                 0
city                     0
state                    0
address                  0
latitude                 0
longitude                0
incident_datetime      340
officer_id               0
officer_first_name       0
officer_last_name        0
badge_number           312
suspect_id               0
suspect_first_name       0
suspect_last_name        0
suspect_age              0
suspect_gender           0
suspect_race             0
victim_id                0
victim_first_name        0
victim_last_name         0
victim_age               0
victim_gender            0
victim_phone             0
weapon_used              0
severity                 0
case_status              0
resolution               0
num_arrests              0
property_loss_usd      436
reported_online          0
notes                 1069
dtype: int64

In [14]:
df['property_loss_usd']=df['property_loss_usd'].fillna(0)

In [15]:
df['notes']=df['notes'].fillna('')

In [16]:
df.isnull().sum()

incident_id             0
crime_type              0
district                0
city                    0
state                   0
address                 0
latitude                0
longitude               0
incident_datetime     340
officer_id              0
officer_first_name      0
officer_last_name       0
badge_number          312
suspect_id              0
suspect_first_name      0
suspect_last_name       0
suspect_age             0
suspect_gender          0
suspect_race            0
victim_id               0
victim_first_name       0
victim_last_name        0
victim_age              0
victim_gender           0
victim_phone            0
weapon_used             0
severity                0
case_status             0
resolution              0
num_arrests             0
property_loss_usd       0
reported_online         0
notes                   0
dtype: int64

In [17]:
df=df.dropna(subset=['incident_datetime'])

In [18]:
df.isnull().sum()

incident_id             0
crime_type              0
district                0
city                    0
state                   0
address                 0
latitude                0
longitude               0
incident_datetime       0
officer_id              0
officer_first_name      0
officer_last_name       0
badge_number          292
suspect_id              0
suspect_first_name      0
suspect_last_name       0
suspect_age             0
suspect_gender          0
suspect_race            0
victim_id               0
victim_first_name       0
victim_last_name        0
victim_age              0
victim_gender           0
victim_phone            0
weapon_used             0
severity                0
case_status             0
resolution              0
num_arrests             0
property_loss_usd       0
reported_online         0
notes                   0
dtype: int64

In [19]:
df.shape

(4910, 33)

In [20]:
df.duplicated().sum()

np.int64(189)

In [21]:
# deleting duplicates
df=df.drop_duplicates()

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
for col in df.select_dtypes(include='object').columns:
    print(f"\n--- {col} ---")
    print(df[col].unique()[:20])

--- incident_id ---

C:\Users\Vivobook\AppData\Local\Temp\ipykernel_14216\1979953971.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

<StringArray>
['INC001115', 'INC004706', 'INC002249', 'INC000021', 'INC000488', 'INC000661',
 'INC001727', 'INC003981', 'INC001205', 'INC000972', 'INC002898', 'INC003264',
 'INC003052', 'INC000524', 'INC000560', 'INC000812', 'INC003999', 'INC003972',
 'INC000949', 'INC002839']
Length: 20, dtype: str

--- crime_type ---
<StringArray>
[              'asslt',            'burglary',            'Homocide',
     'Property Damage',    'Domestc Violence', 'Breaking & Entering',
             'robbery',        'manslaughter',                 'B&E',
           'Narcotics',             'Burglry',               'THEFT',
 'Fraudulent Activity',        'Drug Offense',       'Armed Robbery',
               'Arsen',           'Abduction',            'Graffiti',
            'Trespass',         'CYBER CRIME']
Length: 20, dtype: str

--- district ---
<StringArray>
[        'Sou',  ' southeast', 'Southwest  ',         'Cen',      ' North',
      'East  ',   'southeast',     'midtown',   'northeast',     'CENTRAL',
     'central',         'Eas', 'Northeast  ',         'Nor',  ' Southeast',
   'SOUTHWEST',       'North',       ' East',         'Mid',    '  EAST  ']
Length: 20, dtype: str

--- city ---
<StringArray>
[  'Maplewood',    'Lakewood', 'Springfield',   'Hillcrest', 'Centerville',
   'Riverside',     'Oakdale',    'Fairview']
Length: 8, dtype: str

--- state ---
<StringArray>
['GA', 'OH', 'AZ', 'PA', 'CA', 'TX', 'IL', 'NY', 'FL', 'NC']
Length: 10, dtype: str

--- address ---
<StringArray>
[    '2830 Cedar Lane',        '2361 Park Rd',        '1067 Main St',
 '4713 Washington Ave',       '1371 River Rd',       '3551 Elm Blvd',
     '7394 Cedar Lane',       '1610 River Rd',         '378 Oak Ave',
        '8974 Park Rd',       '9798 Elm Blvd',       '8650 Elm Blvd',
       '5420 River Rd',        '6121 Oak Ave',        '5094 Main St',
       '5556 River Rd',     '6637 Lincoln St',     '3221 Cedar Lane',
        '5783 Main St',     '5563 Lincoln St']
Length: 20, dtype: str

--- incident_datetime ---
<StringArray>
['2024-04-16 08:45:03', '2022-01-11 22:03:29', '2022-04-14 11:39:24',
 '2020-12-09 15:14:24', '2021-07-24 20:08:13',          '05-03-2020',
 '2021-10-03 05:17:02', '2023-09-30 14:49:01', '2021-01-22 02:37:24',
 '2021-03-29 04:16:18', '2020-03-03 06:46:12', '2018-09-09 02:11:36',
 '2020-07-04 13:31:15', '2023-07-30 09:05:34',    '04/01/2020 03:09',
 '2020-11-26 07:15:19', '2021-11-05 17:21:18', '2022-10-07 17:15:25',
 '2024-11-23 19:30:48', '2018-08-26 04:50:54']
Length: 20, dtype: str

--- officer_id ---
<StringArray>
['OFF0078', 'OFF0059', 'OFF0088', 'OFF0077', 'OFF0083', 'OFF0089', 'OFF0141',
 'OFF0008', 'OFF0034', 'OFF0093', 'OFF0035', 'OFF0111', 'OFF0104', 'OFF0014',
 'OFF0046', 'OFF0133', 'OFF0097', 'OFF0020', 'OFF0050', 'OFF0064']
Length: 20, dtype: str

--- officer_first_name ---
<StringArray>
[   'Emily', 'Michelle',  'Michael',    'Chris',    'Susan', 'Jennifer',
    'Karen',   'Daniel',     'Mary',     'John',    'Donna',    'James',
   'Joseph',    'emily',   'Ashley',  'Charles',    'Sarah',  'Jessica',
  'Anthony',    'EMILY']
Length: 20, dtype: str

--- officer_last_name ---
<StringArray>
[   'Davis',    'Green',    'White',  'Jackson',   'Flores',   'Harris',
     'Hall', 'Thompson',    'Jones',   'Taylor',    'Smith',   'Nguyen',
   'Walker',   'Martin',    'Moore',      'Lee',    'Brown', 'Anderson',
   'Torres',    'Scott']
Length: 20, dtype: str

--- suspect_id ---
<StringArray>
['SUS00281', 'SUS00376', 'SUS00560', 'SUS00468', 'SUS00751', 'SUS00454',
 'SUS00623', 'SUS00533', 'SUS00320',  'Unknown', 'SUS00005', 'SUS00783',
 'SUS00236', 'SUS00074', 'SUS00606', 'SUS00776', 'SUS00636', 'SUS00294',
 'SUS00207', 'SUS00385']
Length: 20, dtype: str

--- suspect_first_name ---
<StringArray>
[ 'Barbara',  'Richard',  'Michael',   'Thomas',    'James',    'Carol',
 'Jennifer',   'Robert',  'Unknown',   'Ashley',  'Anthony',   'Daniel',
    'Chris',   'Joseph',     'Mary',    'Donna',    'Karen',    'Sarah',
    'Susan',    'Nancy']
Length: 20, dtype: str

--- suspect_last_name ---
<StringArray>
[  'Thomas',   'Harris',    'Scott',  'Jackson',      'Lee',   'Taylor',
     'Hill',  'Unknown',   'Martin',    'Jones', 'Thompson',   'Garcia',
    'Brown',   'Wright',    'Young',    'Green',    'White',  'Johnson',
    'Moore',   'Torres']
Length: 20, dtype: str

--- suspect_gender ---
<StringArray>
[   'MALE',   'Other',       'F',  'female', 'Unknown',  'Female',       'm',
  'FEMALE',       'M',    'male',    'Male',       'f']
Length: 12, dtype: str

--- suspect_race ---
<StringArray>
[   'asian',    'Black',    'white',    'White',  'Unknown', 'Hispanic',
    'BLACK',    'Asian', 'hispanic',    'Other']
Length: 10, dtype: str

--- victim_id ---
<StringArray>
['VIC00642', 'VIC00262', 'VIC00518', 'VIC00243', 'VIC00512', 'VIC00473',
 'VIC00429', 'VIC00904', 'VIC00093', 'VIC00859', 'VIC00682', 'VIC00084',
 'VIC00960', 'VIC00569', 'VIC00821', 'VIC00071', 'VIC00676', 'VIC00846',
 'VIC00228', 'VIC00850']
Length: 20, dtype: str

--- victim_first_name ---
<StringArray>
[  'Robert',     'John',  'Richard',    'Susan',   'Thomas',  'Anthony',
     'Mary',    'David', 'Michelle',     'Mark',  'Barbara',   'Daniel',
    'Linda',    'Donna', 'Patricia',    'Carol',   'Joseph',  'Charles',
    'James',  'Matthew']
Length: 20, dtype: str

--- victim_last_name ---
<StringArray>
[  'Torres',   'Martin',     'Hill',    'Young',   'Thomas',   'Wilson',
   'Walker',      'Lee',   'Nguyen',   'Taylor',    'Scott',  'Johnson',
  'Jackson', 'Williams',    'Green', 'Anderson',   'Harris',   'Miller',
   'Wright',    'Brown']
Length: 20, dtype: str

--- victim_gender ---
<StringArray>
['Unknown',   'Other',       'M',  'female',    'male',  'Female',       'F',
    'MALE',       'm',       'f',    'Male',  'FEMALE']
Length: 12, dtype: str

--- victim_phone ---
<StringArray>
[  '6223265920', '241-973-4826', '244-584-7696',   '5021227484',
   '9698766873', '590-332-6488', '431-579-6170', '587-505-1798',
   '3956212676', '376-440-3132', '596-444-9767', '855-624-8658',
 '832-278-8736', '655-760-3556',      'Unknown', '628-122-3246',
 '897-102-9006', '924-985-8530', '527-108-7397', '701-395-6824']
Length: 20, dtype: str

--- weapon_used ---
<StringArray>
[     'Firearm',        'KNIFE',        'hands',      'Unarmed',
 'Blunt Object',      'Unknown',        'Rifle',          'Bat',
        'Knife',       'Pistol',      'firearm',          'Gun',
   'Hands/Feet', 'blunt object']
Length: 14, dtype: str

--- severity ---
<StringArray>
[       '2',        '3',        '1',      'Low',   'MEDIUM',     'high',
  'Unknown',     'Crit',     'High',      'low', 'Critical',        '4',
 'CRITICAL',   'Medium',      'Med']
Length: 15, dtype: str

--- case_status ---
<StringArray>
[               'Open',             'Unknown',              'CLOSED',
            'Resolved',              'Closed', 'under investigation',
                'open',        'Investgation', 'Under Investigation',
                'OPEN',              'Pendng',             'Pending',
              'closed']
Length: 13, dtype: str

--- resolution ---
<StringArray>
[     'No Arrest',        'Unknown',        'warning', 'Warning Issued',
    'arrest made',      'NO ARREST',      'Dismissed',    'Arrest Made',
     'Arres Made', 'Case Dismissed']
Length: 10, dtype: str

--- property_loss_usd ---
[0 '44839.49' '15963.38' '48680.14' '23513.01' '19075.36' '34452.47'
 '35339.52' '27438.67' '41738.8' '-34291.84' '3201.56' '37228.41'
 '41473.0' '31931.65' '6546.79' '26845.31' '2167.35' '38573.92' '8534.94']

--- reported_online ---
<StringArray>
['True', 'yes', 'YES', 'False', 'no', 'Unknown', 'Yes', 'No', '1', 'NO', '0']
Length: 11, dtype: str

--- notes ---
<StringArray>
[    'Incident at 2830 Cedar Lane. Officer responded at scene.',
        'Incident at 2361 Park Rd. Officer responded at scene.',
        'Incident at 1067 Main St. Officer responded at scene.',
 'Incident at 4713 Washington Ave. Officer responded at scene.',
                                                             '',
       'Incident at 3551 Elm Blvd. Officer responded at scene.',
     'Incident at 7394 Cedar Lane. Officer responded at scene.',
       'Incident at 1610 River Rd. Officer responded at scene.',
         'Incident at 378 Oak Ave. Officer responded at scene.',
       'Incident at 9798 Elm Blvd. Officer responded at scene.',
       'Incident at 5420 River Rd. Officer responded at scene.',
        'Incident at 6121 Oak Ave. Officer responded at scene.',
        'Incident at 5094 Main St. Officer responded at scene.',
     'Incident at 6637 Lincoln St. Officer responded at scene.',
     'Incident at 3221 Cedar Lane. Officer responded at scene.',
        'Incident at 5783 Main St. Officer responded at scene.',
     'Incident at 5563 Lincoln St. Officer responded at scene.',
     'Incident at 1522 Lincoln St. Officer responded at scene.',
 'Incident at 3806 Washington Ave. Officer responded at scene.',
       'Incident at 3852 River Rd. Officer responded at scene.']
Length: 20, dtype: str

In [24]:
# formats the string typed columns, strip()-cleans spaces at the start and end,title()-only makes the 1st letter uppercase
for col in df.select_dtypes(include='str').columns:
    df[col]=df[col].str.strip().str.title()

In [25]:
df.head()

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,Inc001115,Asslt,Sou,Maplewood,Ga,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,Off0078,...,Unknown,6223265920,Firearm,2,Open,No Arrest,2.0,0,True,Incident At 2830 Cedar Lane. Officer Responded...
1,Inc004706,Burglary,Southeast,Maplewood,Oh,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,Off0059,...,Unknown,241-973-4826,Firearm,3,Unknown,Unknown,2.0,44839.49,Yes,Incident At 2361 Park Rd. Officer Responded At...
2,Inc002249,Homocide,Southwest,Lakewood,Az,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,Off0088,...,Other,244-584-7696,Knife,1,Closed,Warning,2.0,15963.38,Yes,Incident At 1067 Main St. Officer Responded At...
3,Inc000021,Property Damage,Cen,Springfield,Az,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,Off0077,...,Unknown,5021227484,Hands,Low,Resolved,Unknown,5.0,48680.14,False,Incident At 4713 Washington Ave. Officer Respo...
4,Inc000488,Domestc Violence,North,Lakewood,Pa,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,Off0083,...,M,9698766873,Unarmed,Medium,Closed,Warning Issued,2.0,23513.01,Yes,

In [26]:
print(df)

     incident_id        crime_type   district         city state  \
0      Inc001115             Asslt        Sou    Maplewood    Ga
1      Inc004706          Burglary  Southeast    Maplewood    Oh
2      Inc002249          Homocide  Southwest     Lakewood    Az
3      Inc000021   Property Damage        Cen  Springfield    Az
4      Inc000488  Domestc Violence      North     Lakewood    Pa
...          ...               ...        ...          ...   ...
5245   Inc003247          Burglary        Nor  Springfield    Oh
5246   Inc000314          Vandlism  Northwest    Maplewood    Fl
5247   Inc002761             Arson  Northwest     Fairview    Fl
5248   Inc001022              Scam       East    Maplewood    Tx
5249   Inc003216         Vandalism       West  Springfield    Ny

                  address    latitude   longitude    incident_datetime  \
0         2830 Cedar Lane  170.284100  -77.500710  2024-04-16 08:45:03
1            2361 Park Rd   29.422717  -77.167016  2022-01-11 22:03:29
2            1067 Main St   39.411460  -98.615298  2022-04-14 11:39:24
3     4713 Washington Ave   28.633439  -99.030051  2020-12-09 15:14:24
4           1371 River Rd   34.217850 -121.614731  2021-07-24 20:08:13
...                   ...         ...         ...                  ...
5245        4434 Elm Blvd   42.576022  -79.788519  2021-12-18 17:27:18
5246     1065 Sunset Blvd   38.941858 -108.480924  2023-06-23 04:09:19
5247     6419 Sunset Blvd   41.627732  -82.048681  2018-04-25 14:38:24
5248        9087 River Rd   28.903176 -111.840384  2023-03-29 09:54:50
5249     3781 Sunset Blvd   30.859979  -78.590392           09-08-2022

     officer_id  ... victim_gender  victim_phone   weapon_used  severity  \
0       Off0078  ...       Unknown    6223265920       Firearm         2
1       Off0059  ...       Unknown  241-973-4826       Firearm         3
2       Off0088  ...         Other  244-584-7696         Knife         1
3       Off0077  ...       Unknown    5021227484         Hands       Low
4       Off0083  ...             M    9698766873       Unarmed    Medium
...         ...  ...           ...           ...           ...       ...
5245    Off0005  ...             M  534-870-3834       Unknown    Medium
5246    Off0132  ...        Female       Unknown       Unknown         2
5247    Off0003  ...         Other  796-911-1169  Blunt Object         4
5248    Off0028  ...        Female  214-897-2917       Unknown   Unknown
5249    Off0102  ...       Unknown       Unknown       Unknown  Critical

     case_status      resolution  num_arrests property_loss_usd  \
0           Open       No Arrest          2.0                 0
1        Unknown         Unknown          2.0          44839.49
2         Closed         Warning          2.0          15963.38
3       Resolved         Unknown          5.0          48680.14
4         Closed  Warning Issued          2.0          23513.01
...          ...             ...          ...               ...
5245     Unknown     Arrest Made          2.0          44417.98
5246     Pending         Unknown          5.0          16330.48
5247      Closed         Unknown          4.0          13138.25
5248      Closed     Arrest Made          1.0          43851.12
5249        Open     Arrest Made          2.0          38856.84

     reported_online                                              notes
0               True  Incident At 2830 Cedar Lane. Officer Responded...
1                Yes  Incident At 2361 Park Rd. Officer Responded At...
2                Yes  Incident At 1067 Main St. Officer Responded At...
3              False  Incident At 4713 Washington Ave. Officer Respo...
4                Yes
...              ...                                                ...
5245         Unknown
5246              No  Incident At 1065 Sunset Blvd. Officer Responde...
5247         Unknown  Incident At 6419 Sunset Blvd. Officer Responde...
5248               0  Incident At 9087 River Rd. Officer Responded A...
5249              No  Incident At 3781 Sunset Blvd. Officer Responde...

[4721 rows x 33 columns]

In [27]:
df.isnull().sum()

incident_id             0
crime_type              0
district                0
city                    0
state                   0
address                 0
latitude                0
longitude               0
incident_datetime       0
officer_id              0
officer_first_name      0
officer_last_name       0
badge_number          281
suspect_id              0
suspect_first_name      0
suspect_last_name       0
suspect_age             0
suspect_gender          0
suspect_race            0
victim_id               0
victim_first_name       0
victim_last_name        0
victim_age              0
victim_gender           0
victim_phone            0
weapon_used             0
severity                0
case_status             0
resolution              0
num_arrests             0
property_loss_usd       0
reported_online         0
notes                   0
dtype: int64

In [28]:
df['badge_number']=df['badge_number'].fillna('Unknown')

In [29]:
df.isnull().sum()

incident_id           0
crime_type            0
district              0
city                  0
state                 0
address               0
latitude              0
longitude             0
incident_datetime     0
officer_id            0
officer_first_name    0
officer_last_name     0
badge_number          0
suspect_id            0
suspect_first_name    0
suspect_last_name     0
suspect_age           0
suspect_gender        0
suspect_race          0
victim_id             0
victim_first_name     0
victim_last_name      0
victim_age            0
victim_gender         0
victim_phone          0
weapon_used           0
severity              0
case_status           0
resolution            0
num_arrests           0
property_loss_usd     0
reported_online       0
notes                 0
dtype: int64

In [30]:
df['crime_type'].unique()

<StringArray>
[              'Asslt',            'Burglary',            'Homocide',
     'Property Damage',    'Domestc Violence', 'Breaking & Entering',
             'Robbery',        'Manslaughter',                 'B&E',
           'Narcotics',             'Burglry',               'Theft',
 'Fraudulent Activity',        'Drug Offense',       'Armed Robbery',
               'Arsen',           'Abduction',            'Graffiti',
            'Trespass',         'Cyber Crime',         'Trespassing',
      'Sexual Assault',               'Fraud',       'Theft/Larceny',
             'Larceny',               'Arson',            'Homicide',
        'Tresspassing',          'Cybercrime',             'Hacking',
             'Assault',      'Sexual Assualt',        'Fire Setting',
        'Drug Offence',       'Drunk Driving',                'Duii',
              'Robbry',           'Vandalism',            'Vandlism',
          'Kidnapping',              'D.U.I.',             'Roberry',
   'Assault & Battery',   'Domestic Violence',                'Scam',
           'Kidnaping',         'Sex Assault',       'Dom. Violence',
                  'Sa',           'Deception',             'Battery',
                 'Dwi',                  'Dv',                 'Dui',
               'Drugs',        'Online Fraud',              'Murder',
            'Stealing', 'Assault  &  Battery',     'Sexual  Assualt',
     'Sexual  Assault',        'Sex  Assault',  'Domestic  Violence',
       'Drug  Offense',    'Property  Damage',       'Drug  Offence',
      'Armed  Robbery',        'Cyber  Crime']
Length: 68, dtype: str

In [31]:
df['crime_type'] = df['crime_type'].str.strip().str.replace(r'\s+', ' ', regex=True)

In [32]:
crime_map = {
    'Asslt': 'Assault', 'Assault': 'Assault', 'Assault & Battery': 'Assault', 'Battery': 'Assault',
    'Burglary': 'Burglary', 'Burglry': 'Burglary', 'Breaking & Entering': 'Burglary', 'B&E': 'Burglary',
    'Homocide': 'Homicide', 'Homicide': 'Homicide', 'Murder': 'Homicide', 'Manslaughter': 'Homicide',
    'Property Damage': 'Property Damage',
    'Vandalism': 'Vandalism', 'Vandlism': 'Vandalism', 'Graffiti': 'Vandalism',
    'Domestc Violence': 'Domestic Violence', 'Domestic Violence': 'Domestic Violence',
    'Dom. Violence': 'Domestic Violence', 'Dv': 'Domestic Violence',
    'Narcotics': 'Drug Offense', 'Drug Offense': 'Drug Offense', 'Drug Offence': 'Drug Offense', 'Drugs': 'Drug Offense',
    'Robbery': 'Robbery', 'Robbry': 'Robbery', 'Roberry': 'Robbery',
    'Armed Robbery': 'Armed Robbery',
    'Theft': 'Theft/Larceny', 'Theft/Larceny': 'Theft/Larceny', 'Larceny': 'Theft/Larceny', 'Stealing': 'Theft/Larceny',
    'Fraudulent Activity': 'Fraud', 'Fraud': 'Fraud', 'Scam': 'Fraud', 'Deception': 'Fraud', 'Online Fraud': 'Fraud',
    'Arsen': 'Arson', 'Arson': 'Arson', 'Fire Setting': 'Arson',
    'Abduction': 'Kidnapping', 'Kidnapping': 'Kidnapping', 'Kidnaping': 'Kidnapping',
    'Trespass': 'Trespassing', 'Trespassing': 'Trespassing', 'Tresspassing': 'Trespassing',
    'Cyber Crime': 'Cyber Crime', 'Cybercrime': 'Cyber Crime', 'Hacking': 'Cyber Crime',
    'Sexual Assault': 'Sexual Assault', 'Sexual Assualt': 'Sexual Assault', 'Sex Assault': 'Sexual Assault', 'Sa': 'Sexual Assault',
    'Drunk Driving': 'DUI', 'Duii': 'DUI', 'D.U.I.': 'DUI', 'Dwi': 'DUI', 'Dui': 'DUI',
}

df['crime_type'] = df['crime_type'].map(crime_map)

In [33]:
df['crime_type'].isnull().sum()

np.int64(0)

In [34]:
original = pd.read_csv("C:/Users/Vivobook/Downloads/python-project/crime_incidents_messy.csv")
df['crime_type'] = original['crime_type']
df['crime_type'] = df['crime_type'].str.strip().str.replace(r'\s+', ' ', regex=True).str.lower()

# Check what's actually in the column now, before mapping
print(df['crime_type'].unique())
crime_map = {
    'asslt': 'Assault', 'assault': 'Assault', 'assault & battery': 'Assault', 'battery': 'Assault',
    'burglary': 'Burglary', 'burglry': 'Burglary', 'breaking & entering': 'Burglary', 'b&e': 'Burglary',
    'homocide': 'Homicide', 'homicide': 'Homicide', 'murder': 'Homicide', 'manslaughter': 'Homicide',
    'property damage': 'Property Damage',
    'vandalism': 'Vandalism', 'vandlism': 'Vandalism', 'graffiti': 'Vandalism',
    'domestc violence': 'Domestic Violence', 'domestic violence': 'Domestic Violence',
    'dom. violence': 'Domestic Violence', 'dv': 'Domestic Violence',
    'narcotics': 'Drug Offense', 'drug offense': 'Drug Offense', 'drug offence': 'Drug Offense', 'drugs': 'Drug Offense',
    'robbery': 'Robbery', 'robbry': 'Robbery', 'roberry': 'Robbery',
    'armed robbery': 'Armed Robbery',
    'theft': 'Theft/Larceny', 'theft/larceny': 'Theft/Larceny', 'larceny': 'Theft/Larceny', 'stealing': 'Theft/Larceny',
    'fraudulent activity': 'Fraud', 'fraud': 'Fraud', 'scam': 'Fraud', 'deception': 'Fraud', 'online fraud': 'Fraud',
    'arsen': 'Arson', 'arson': 'Arson', 'fire setting': 'Arson',
    'abduction': 'Kidnapping', 'kidnapping': 'Kidnapping', 'kidnaping': 'Kidnapping',
    'trespass': 'Trespassing', 'trespassing': 'Trespassing', 'tresspassing': 'Trespassing',
    'cyber crime': 'Cyber Crime', 'cybercrime': 'Cyber Crime', 'hacking': 'Cyber Crime',
    'sexual assault': 'Sexual Assault', 'sexual assualt': 'Sexual Assault', 'sex assault': 'Sexual Assault', 'sa': 'Sexual Assault',
    'drunk driving': 'DUI', 'duii': 'DUI', 'd.u.i.': 'DUI', 'dwi': 'DUI', 'dui': 'DUI',
}

df['crime_type'] = df['crime_type'].map(crime_map)

<StringArray>
[              'asslt',            'burglary',            'homocide',
     'property damage',    'domestc violence', 'breaking & entering',
             'robbery',        'manslaughter',                 'b&e',
           'narcotics',             'burglry',               'theft',
 'fraudulent activity',        'drug offense',       'armed robbery',
               'arsen',           'abduction',            'graffiti',
            'trespass',         'cyber crime',         'trespassing',
      'sexual assault',               'fraud',       'theft/larceny',
             'larceny',               'arson',            'homicide',
        'tresspassing',          'cybercrime',             'hacking',
             'assault',      'sexual assualt',        'fire setting',
        'drug offence',       'drunk driving',                'duii',
              'robbry',           'vandalism',            'vandlism',
          'kidnapping',              'd.u.i.',             'roberry',
   'assault & battery',   'domestic violence',                'scam',
           'kidnaping',         'sex assault',       'dom. violence',
                  'sa',           'deception',             'battery',
                 'dwi',                  'dv',                 'dui',
               'drugs',        'online fraud',              'murder',
            'stealing']
Length: 58, dtype: str

In [35]:
(df['crime_type'].isnull().sum())

np.int64(0)

In [36]:
df['crime_type'].value_counts()

crime_type
Fraud                415
DUI                  340
Drug Offense         331
Arson                329
Homicide             316
Theft/Larceny        314
Kidnapping           311
Sexual Assault       310
Domestic Violence    294
Trespassing          289
Cyber Crime          289
Burglary             288
Assault              286
Robbery              269
Vandalism            263
Property Damage       42
Armed Robbery         35
Name: count, dtype: int64

In [37]:
print(df['crime_type'].unique())

<StringArray>
[          'Assault',          'Burglary',          'Homicide',
   'Property Damage', 'Domestic Violence',           'Robbery',
      'Drug Offense',     'Theft/Larceny',             'Fraud',
     'Armed Robbery',             'Arson',        'Kidnapping',
         'Vandalism',       'Trespassing',       'Cyber Crime',
    'Sexual Assault',               'DUI']
Length: 17, dtype: str

In [38]:
original = pd.read_csv("C:/Users/Vivobook/Downloads/python-project/crime_incidents_messy.csv")
df['crime_type'] = original['crime_type']

df['crime_type'] = df['crime_type'].str.strip().str.replace(r'\s+', ' ', regex=True).str.lower()

crime_map = {
    'asslt': 'Assault', 'assault': 'Assault', 'assault & battery': 'Assault', 'battery': 'Assault',
    'burglary': 'Burglary', 'burglry': 'Burglary', 'breaking & entering': 'Burglary', 'b&e': 'Burglary',
    'homocide': 'Homicide', 'homicide': 'Homicide', 'murder': 'Homicide', 'manslaughter': 'Homicide',
    'property damage': 'Property Damage',
    'vandalism': 'Vandalism', 'vandlism': 'Vandalism', 'graffiti': 'Vandalism',
    'domestc violence': 'Domestic Violence', 'domestic violence': 'Domestic Violence',
    'dom. violence': 'Domestic Violence', 'dv': 'Domestic Violence',
    'narcotics': 'Drug Offense', 'drug offense': 'Drug Offense', 'drug offence': 'Drug Offense', 'drugs': 'Drug Offense',
    'robbery': 'Robbery', 'robbry': 'Robbery', 'roberry': 'Robbery',
    'armed robbery': 'Armed Robbery',
    'theft': 'Theft/Larceny', 'theft/larceny': 'Theft/Larceny', 'larceny': 'Theft/Larceny', 'stealing': 'Theft/Larceny',
    'fraudulent activity': 'Fraud', 'fraud': 'Fraud', 'scam': 'Fraud', 'deception': 'Fraud', 'online fraud': 'Fraud',
    'arsen': 'Arson', 'arson': 'Arson', 'fire setting': 'Arson',
    'abduction': 'Kidnapping', 'kidnapping': 'Kidnapping', 'kidnaping': 'Kidnapping',
    'trespass': 'Trespassing', 'trespassing': 'Trespassing', 'tresspassing': 'Trespassing',
    'cyber crime': 'Cyber Crime', 'cybercrime': 'Cyber Crime', 'hacking': 'Cyber Crime',
    'sexual assault': 'Sexual Assault', 'sexual assualt': 'Sexual Assault', 'sex assault': 'Sexual Assault', 'sa': 'Sexual Assault',
    'drunk driving': 'DUI', 'duii': 'DUI', 'd.u.i.': 'DUI', 'dwi': 'DUI', 'dui': 'DUI',
}

df['crime_type'] = df['crime_type'].map(crime_map)

print(df['crime_type'].isnull().sum())

0

In [39]:
df['crime_type'].value_counts()

crime_type
Fraud                415
DUI                  340
Drug Offense         331
Arson                329
Homicide             316
Theft/Larceny        314
Kidnapping           311
Sexual Assault       310
Domestic Violence    294
Trespassing          289
Cyber Crime          289
Burglary             288
Assault              286
Robbery              269
Vandalism            263
Property Damage       42
Armed Robbery         35
Name: count, dtype: int64

In [40]:
df['district'].unique()

<StringArray>
[      'Sou', 'Southeast', 'Southwest',       'Cen',     'North',      'East',
   'Midtown', 'Northeast',   'Central',       'Eas',       'Nor',       'Mid',
     'South',       'Wes',      'West', 'Northwest']
Length: 16, dtype: str

In [41]:
df['district']=df['district'].str.strip().str.replace(r'\s+','',regex=True).str.lower()
district_map = {
    'sou': 'South', 'south': 'South',
    'nor': 'North', 'north': 'North',
    'eas': 'East', 'east': 'East',
    'wes': 'West', 'west': 'West',
    'cen': 'Central', 'central': 'Central',
    'mid': 'Midtown', 'midtown': 'Midtown',
    'northeast': 'Northeast', 'ne': 'Northeast',
    'northwest': 'Northwest', 'nw': 'Northwest',
    'southwest': 'Southwest', 'sw': 'Southwest',
    'southeast': 'Southeast', 'se': 'Southeast'
}
df['district'] = df['district'].map(district_map)

In [42]:
df['district'].isnull().sum()

np.int64(0)

In [43]:
df['district'].unique()

<StringArray>
[    'South', 'Southeast', 'Southwest',   'Central',     'North',      'East',
   'Midtown', 'Northeast',      'West', 'Northwest']
Length: 10, dtype: str

In [44]:
df['state']=df['state'].str.strip().str.upper()
df['state'].unique()

<StringArray>
['GA', 'OH', 'AZ', 'PA', 'CA', 'TX', 'IL', 'NY', 'FL', 'NC']
Length: 10, dtype: str

In [45]:
df['city']=df['city'].str.strip().str.title()
df['city'].unique()

<StringArray>
[  'Maplewood',    'Lakewood', 'Springfield',   'Hillcrest', 'Centerville',
   'Riverside',     'Oakdale',    'Fairview']
Length: 8, dtype: str

In [46]:
df['severity'].unique()

<StringArray>
[       '2',        '3',        '1',      'Low',   'Medium',     'High',
  'Unknown',     'Crit', 'Critical',        '4',      'Med']
Length: 11, dtype: str

In [47]:
severity_map= {
    '1' : 'Low', 'low' : 'Low',
    '2' : 'Medium' , 'medium' : 'Medium' , 'med' : 'Medium' , 
    '3' : 'High' , 'high' : 'High', 
    '4': 'Critical', 'critical': 'Critical', 'crit': 'Critical',
    'unknown': 'Unknown'
}

df['severity']= df['severity'].astype(str).str.strip().str.lower().map(severity_map)
df['severity'].isnull().sum()
df['severity'].unique()

<StringArray>
['Medium', 'High', 'Low', 'Unknown', 'Critical']
Length: 5, dtype: str

In [48]:
df['reported_online'].unique()

<StringArray>
['True', 'Yes', 'False', 'No', 'Unknown', '1', '0']
Length: 7, dtype: str

In [49]:
reported_map = {
    'true' : 'True' , 'yes' : 'True' , '1' : 'True' , 
    'false' : 'False' , 'no' : 'False' , '0' : 'False' , 
    'unknown' : 'Unknown'
}

df['reported_online'] = df['reported_online'].astype(str).str.strip().str.lower().map(reported_map)
print(df['reported_online'].isnull().sum())
print(df['reported_online'].unique())

0
<StringArray>
['True', 'False', 'Unknown']
Length: 3, dtype: str

In [50]:
df['suspect_gender'].unique()

<StringArray>
['Male', 'Other', 'F', 'Female', 'Unknown', 'M']
Length: 6, dtype: str

In [51]:
df['victim_gender'].unique()

<StringArray>
['Unknown', 'Other', 'M', 'Female', 'Male', 'F']
Length: 6, dtype: str

In [52]:
gender_map = {
    'F' : 'Female' , 'M' : 'Male' ,
    'female' : 'Female' , 'male' : 'Male',
    'other' : 'Other' , 'unknown' : 'Unknown' 
}

df['suspect_gender'] = df['suspect_gender'].astype(str).str.strip().str.lower().map(gender_map)
df['victim_gender'] = df['victim_gender'].astype(str).str.strip().str.lower().map(gender_map)

df['victim_gender'] = df['victim_gender'].fillna('Unknown')
df['suspect_gender'] = df['suspect_gender'].fillna('Unknown')

df['suspect_gender'].isnull().sum()
df['victim_gender'].isnull().sum()

np.int64(0)

In [53]:
df['suspect_gender'].unique()

<StringArray>
['Male', 'Other', 'Unknown', 'Female']
Length: 4, dtype: str

In [54]:
df['victim_gender'].unique()

<StringArray>
['Unknown', 'Other', 'Female', 'Male']
Length: 4, dtype: str

In [55]:
df['victim_phone'].unique()

<StringArray>
[  '6223265920', '241-973-4826', '244-584-7696',   '5021227484',
   '9698766873', '590-332-6488', '431-579-6170', '587-505-1798',
   '3956212676', '376-440-3132',
 ...
 '884-437-3530', '623-741-2127', '867-340-6134', '301-777-9335',
 '754-629-2414', '738-902-6365', '953-979-4479', '534-870-3834',
 '796-911-1169', '214-897-2917']
Length: 3741, dtype: str

In [56]:
import re

def clean_phone(val):
    val = str(val)
    if val.lower() in ['nan', 'unknown']:
        return 'Unknown'
    digits = re.sub(r'\D', '', val)  # strip everything except digits
    if len(digits) == 10:
        return f"{digits[0:3]}-{digits[3:6]}-{digits[6:10]}"
    return 'Unknown' 

df['victim_phone'] = df['victim_phone'].apply(clean_phone)

In [57]:
df['victim_phone'].unique()

<StringArray>
['622-326-5920', '241-973-4826', '244-584-7696', '502-122-7484',
 '969-876-6873', '590-332-6488', '431-579-6170', '587-505-1798',
 '395-621-2676', '376-440-3132',
 ...
 '884-437-3530', '623-741-2127', '867-340-6134', '301-777-9335',
 '754-629-2414', '738-902-6365', '953-979-4479', '534-870-3834',
 '796-911-1169', '214-897-2917']
Length: 3741, dtype: str

In [58]:
df['victim_phone'].isnull().sum()

np.int64(0)

In [59]:
df['incident_datetime'].unique()

<StringArray>
['2024-04-16 08:45:03', '2022-01-11 22:03:29', '2022-04-14 11:39:24',
 '2020-12-09 15:14:24', '2021-07-24 20:08:13',          '05-03-2020',
 '2021-10-03 05:17:02', '2023-09-30 14:49:01', '2021-01-22 02:37:24',
 '2021-03-29 04:16:18',
 ...
 '2023-11-26 16:27:41', '2019-12-04 03:38:33', '2024-01-06 16:30:04',
 '2020-02-19 05:09:52', '2020-03-25 05:55:21', '2021-12-18 17:27:18',
 '2023-06-23 04:09:19', '2018-04-25 14:38:24', '2023-03-29 09:54:50',
          '09-08-2022']
Length: 4675, dtype: str

In [60]:
df['incident_datetime'] = pd.to_datetime(df['incident_datetime'], errors='coerce')

print(df['incident_datetime'].isnull().sum())

df[]

SyntaxError: invalid syntax (2765266857.py, line 5)

In [ ]:
original = pd.read_csv("C:/Users/Vivobook/Downloads/python-project/crime_incidents_messy.csv")

# Get the incident_ids of the rows that failed to parse
failed_ids = df.loc[df['incident_datetime'].isnull(), 'incident_id']

# Look up those same incident_ids in the original file
print(original[original['incident_id'].isin(failed_ids)]['incident_datetime'].unique()[:20])

In [ ]:
print(df['incident_id'].head())
print(original['incident_id'].head())

In [ ]:
failed_ids = df.loc[df['incident_datetime'].isnull(), 'incident_id'].str.upper()

print(original[original['incident_id'].str.upper().isin(failed_ids)]['incident_datetime'].unique()[:20])

In [ ]:
# Start fresh from the original column
original = pd.read_csv("C:/Users/Vivobook/Downloads/python-project/crime_incidents_messy.csv")
df['incident_datetime'] = original['incident_datetime']

# Identify each pattern precisely
iso_mask = df['incident_datetime'].str.match(r'^\d{4}-\d{2}-\d{2}', na=False)      # 2024-04-16 08:45:03
dash_mask = df['incident_datetime'].str.match(r'^\d{2}-\d{2}-\d{4}', na=False)     # 05-03-2020 (DD-MM-YYYY)
slash_mask = df['incident_datetime'].str.contains('/', na=False)                   # 04/01/2020 03:09 (MM/DD/YYYY)

# Parse each group with the correct rule
df.loc[iso_mask, 'incident_datetime'] = pd.to_datetime(df.loc[iso_mask, 'incident_datetime'], errors='coerce')
df.loc[dash_mask, 'incident_datetime'] = pd.to_datetime(df.loc[dash_mask, 'incident_datetime'], dayfirst=True, errors='coerce')
df.loc[slash_mask, 'incident_datetime'] = pd.to_datetime(df.loc[slash_mask, 'incident_datetime'], dayfirst=False, errors='coerce')

# Final conversion to proper datetime dtype
df['incident_datetime'] = pd.to_datetime(df['incident_datetime'], errors='coerce')

print(df['incident_datetime'].isnull().sum())
print(df['incident_datetime'].head())

In [ ]:
# Start fresh from the original column
original = pd.read_csv("C:/Users/Vivobook/Downloads/python-project/crime_incidents_messy.csv")
raw = original['incident_datetime']

# Identify each pattern precisely
iso_mask = raw.str.match(r'^\d{4}-\d{2}-\d{2}', na=False)
dash_mask = raw.str.match(r'^\d{2}-\d{2}-\d{4}', na=False)
slash_mask = raw.str.contains('/', na=False)

# Parse each group into a NEW datetime series (don't touch df yet)
parsed = pd.Series(pd.NaT, index=raw.index)
parsed[iso_mask] = pd.to_datetime(raw[iso_mask], errors='coerce')
parsed[dash_mask] = pd.to_datetime(raw[dash_mask], dayfirst=True, errors='coerce')
parsed[slash_mask] = pd.to_datetime(raw[slash_mask], dayfirst=False, errors='coerce')

# Now assign the fully-built datetime series to df in one go
df['incident_datetime'] = parsed

print(df['incident_datetime'].isnull().sum())
print(df['incident_datetime'].head())

In [ ]:
df.to_csv('crime_data_cleaned.csv',index=False)